### ISSUE TITLE
Shell - Fix lack of OAuth roles

### ISSUE THREAD

**Issue by BLaurent** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#295]
Hi,

I am using the     
`<version>1.2.0.BUILD-SNAPSHOT</version>
`

with the following config in application.yml

```
spring:
  cloud:
    dataflow:
      security:
        authorization:
          enabled: false
      server:
        cloudfoundry:
          debugReactor: true

security:
  basic:
    enabled: true
    realm: Spring Cloud Data Flow
  oauth2:
    client:
      client-id: xxxx
      client-secret: xxx
      access-token-uri: https://xxxx.predix-uaa.run.aws-usw02-pr.ice.predix.io/oauth/token
      user-authorization-uri: https://xxxx.predix-uaa.run.aws-usw02-pr.ice.predix.io/oauth/authorize
    resource:
      user-info-uri: https://xxxx.predix-uaa.run.aws-usw02-pr.ice.predix.io/userinfo

management:
  contextPath: /management
  security:
    enabled: true
```

But the dashboard in still showing : 
```
Roles Missing

It appears that you are missing the proper roles to use the Dashboard. Please contact your administrator to rectify the situation.
```

In the shell I have:
```
server-unknown:>app list
Command 'app list' was found but is not currently available (type 'help' then ENTER to learn about this command)
```

What should I do to disable the Roles

Thanks in advance
Regards
