### ISSUE TITLE
Spring Cloud Dataflow deployment on prem Cloud Foundry: can't create `taskService` bean

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#405]
_From @iferca on April 19, 2018 17:43_

Getting error when deploying SCDF in on prem CF using manifest with error: `cant create taskService bean`. As per doc I should pass: 

`SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_TASK_SERVICES my_mysql`

I'm replacing 1.2 version with 1.4. I used to pass spring Datasource properties. Is user provided service the only way? If I have to use that approach, how the service content should look like so SCDF will find what it needs there? In the docs is assumed PCF and service created as marketplace service. 

https://stackoverflow.com/questions/49926638/spring-cloud-dataflow-deployment-on-premises-cloud-foundry

_Copied from original issue: spring-cloud/spring-cloud-dataflow#2153_

**Comment by iferca** [comment]
Sorry for reposting, was trying to reach out in Gitter with no success too :( 

This is my manifest: 
```
applications:
- name: vc-data-flow-server-1-4-0
  host: vc-data-flow-server-1-4-0
  memory: 2G
  disk_quota: 2G
  instances: 1
  path: ./spring-cloud-dataflow-server-cloudfoundry-1.4.0.RELEASE.jar
  env:
    SPRING_APPLICATION_NAME: vc-data-flow-server
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_URL: {API}
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_ORG: {org}
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SPACE: {space}
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_DOMAIN: mcf-np.local
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_USERNAME: vc-cf-api-user
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_PASSWORD: {password}
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SKIP_SSL_VALIDATION: false
    SPRING_APPLICATION_JSON: '{ "maven": { "remote-repositories": { "repo1": { "url": "https://nexus.platforms..../", "auth": { "username": "user", "password": "passwd" } } } } }'
    ENDPOINTS_SENSITIVE: false
    ENDPOINTS_INFO_SENSITIVE: false
    SPRING_DATASOURCE_URL: 'jdbc:postgresql://dbserver:5432/db'
    SPRING_DATASOURCE_USERNAME: 'valuecapture'
    SPRING_DATASOURCE_PASSWORD: 'passwd'
    SPRING_DATASOURCE_DRIVER-CLASS-NAME: 'org.postgresql.Driver'
    HIBERNATE_DIALECT: 'org.hibernate.dialect.PostgreSQLDialect'
    SPRING_DATAFLOW_EMBEDDED_DATABASE_ENABLED: 'false'
services: [syslog, vc-redis]
```

I'm not sure how this `taskService` bean is created from the `SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_TASK_SERVICES` property so not sure even how to create the service in CF if that is the only way. 
We can move the conversation to StackOverflow until is determined is an issue (at least in documentation)
