### ISSUE TITLE
simple ticktock stream

### ISSUE THREAD

**Issue by channing-jackson** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#98]
I have been away for about 5 weeks, and it looks like a lot has changed.  I'm trying to get back up to speed, so please excuse if I ask a dumb question or two...

Using the 1.0.0.M2 cloudfoundry server from here: 
[http://repo.spring.io/milestone/org/springframework/cloud/spring-cloud-dataflow-server-cloudfoundry/1.0.0.M2/](http://repo.spring.io/milestone/org/springframework/cloud/spring-cloud-dataflow-server-cloudfoundry/1.0.0.M2/)

Pushed and configured as was the previously successful mechanisms - basically just following the instructions. 

First, I found I had to explicitly register the time-source and log-sink modules because they were not available OOTB anymore.  Was this by design? 

Secondly, the ticktock stream will not deploy in my environment.  The stream can be created without much trouble.  However, it will not deploy, and no errors or stacktrace arise.  However, if I attempt to explicitly start the ticktock-log or ticktock-time applications (using CLI `cf start ticktock-log`) the following stack trace appears: 

`
2016-05-12T14:55:20.34-0600 [APP/0]      ERR Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/boot/SpringApplication
2016-05-12T14:55:20.34-0600 [APP/0]      ERR    at org.springframework.cloud.stream.module.log.LogSinkApplication.main(LogSinkApplication.java:26)
2016-05-12T14:55:20.34-0600 [APP/0]      ERR Caused by: java.lang.ClassNotFoundException: org.springframework.boot.SpringApplication
2016-05-12T14:55:20.34-0600 [APP/0]      ERR    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
2016-05-12T14:55:20.34-0600 [APP/0]      ERR    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
2016-05-12T14:55:20.34-0600 [APP/0]      ERR    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
2016-05-12T14:55:20.34-0600 [APP/0]      ERR    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
2016-05-12T14:55:20.34-0600 [APP/0]      ERR    ... 1 more
2016-05-12T14:55:20.34-0600 [APP/0]      OUT Exit status 1
2016-05-12T14:55:20.34-0600 [CELL/0]     OUT Exit status 0
2016-05-12T14:55:20.42-0600 [CELL/0]     OUT Creating container
2016-05-12T14:55:20.77-0600 [CELL/0]     OUT Successfully created container
2016-05-12T14:55:23.74-0600 [APP/0]      ERR Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/boot/SpringApplication
2016-05-12T14:55:23.74-0600 [APP/0]      ERR    at org.springframework.cloud.stream.module.log.LogSinkApplication.main(LogSinkApplication.java:26)
2016-05-12T14:55:23.74-0600 [APP/0]      ERR Caused by: java.lang.ClassNotFoundException: org.springframework.boot.SpringApplication
2016-05-12T14:55:23.74-0600 [APP/0]      ERR    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
2016-05-12T14:55:23.74-0600 [APP/0]      ERR    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
2016-05-12T14:55:23.74-0600 [APP/0]      ERR    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
2016-05-12T14:55:23.74-0600 [APP/0]      ERR    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
2016-05-12T14:55:23.74-0600 [APP/0]      ERR    ... 1 more
`

One thing suspicious that I notice is that the apps spawned by creating the stream 'ticktock-time' and 'ticktock-log' do not inherit many of the environment variables that were set on the instance of dataflow server.

**Comment by sabbyanandan** [comment]
@channing-jackson: Between M2 -> M3, there have been core design changes and it is largely complete. We are in the process of stabilizing the contracts for the upcoming RC release. More details in the [release blog](https://spring.io/blog/2016/04/29/spring-cloud-data-flow-1-0-0-m3-released).

That said,

1. Are you using **1.0.0.M2** release of SCDF's Cloud Foundry Server? If yes, you'd have to use this server with **1.0.0.M3** release of Shell. There's compatibility matrix in the [project site](https://cloud.spring.io/spring-cloud-dataflow/) for reference.
2. Please make sure you follow the steps as described in the [reference guide](http://docs.spring.io/spring-cloud-dataflow-server-cloudfoundry/docs/current-SNAPSHOT/reference/htmlsingle/#getting-started). There have been changes to env-var's. Double check the env-var tokens and the credentials. 

> First, I found I had to explicitly register the time-source and log-sink modules because they were not available OOTB anymore. Was this by design?

Yes, it is by design. We wanted to keep it open and flexible, so users can choose and [register](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-docs/src/main/asciidoc/streams.adoc#register-a-stream-app) relevant apps that are necessary for their use-case requirements. You can register applications individually or in bulk and even from the GUI, too. Perhaps also double check the registration command and `--uri` format.

**Comment by channing-jackson** [comment]
@sabbyanandan I followed the instructions, except that I used a YAML file for the configuration. 

Here is my YAML: 
```
applications: 
- name: ckj-scdf
  instances: 1
  memory: 1024M
  disk_quota: 1024M
  no-route: false
  no-hostname: false
  health-check-type: 'port' 
  buildpack: blah_java_buildpack_offline
  env: 
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_API_ENDPOINT: https://api.scp1sysbdv.blah.com
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_BUILDPACK: blah_java_buildpack_offline
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_ORGANIZATION: OrganizationName
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SPACE: SpaceName
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_DOMAIN: server.blah.com
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SERVICES: scdf-redis,rabbit
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SKIP_SSL_VALIDATION: true
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_USERNAME: username
    SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_PASSWORD: password
    JAVA_OPTS: -Dhttp.keepAlive=false
    MAVEN_REMOTE_REPOSITORIES: https://mavenrepo.blah.com/nexus/content/repositories/snapshots/,https://mavenrepo.blah.com/nexus/content/repositories/releases/,https://mavenrepo.blah.com/nexus/content/repositories/spring-milestones/,https://mavenrepo.blah.com/nexus/content/repositories/spring-snapshots/,https://mavenrepo.blah.com/nexus/content/repositories/spring-release/
  services: 
    - scdf-redis
    - rabbit
```

The server application starts just fine.  I'm using the 1.0.0.M2 cloudfoundry server application.  I'm using the 1.0.0.M3 shell application. 

I registered the time and log applications using these shell commands: 
```
module register --name log --type sink --uri maven://org.springframework.cloud.stream.module:log-sink:jar:1.0.0.M2
module register --name time --type source --uri maven://org.springframework.cloud.stream.module:time-source:jar:1.0.0.M2
```

I created the stream using this shell command: 
```
stream create --name ticktock --definition "time | log" --deploy
```

This is the stacktrace resulting from that: 
```
Creating container
Successfully created container
Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/boot/SpringApplication
   at org.springframework.cloud.stream.module.log.LogSinkApplication.main(LogSinkApplication.java:26)
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.SpringApplication
   at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
   at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
   ... 1 more
```
